package metatype

import "github.com/Jasrags/ShadowMUD/common/shared"

var CoreMetatypes = map[string]Metatype{
	"human": {
		ID:          "human",
		Name:        "Human",
		PointCost:   0,
		Category:    CategoryMetahuman,
		Description: "Humans are the most common metatype in the world. They are known for their adaptability and versatility.",
		Attributes: Attributes{
			"agility":    {Name: "Agility", Min: 1, Max: 6, AugMax: 10},
			"body":       {Name: "Body", Min: 1, Max: 6, AugMax: 10},
			"charisma":   {Name: "Charisma", Min: 1, Max: 6, AugMax: 10},
			"edge":       {Name: "Edge", Min: 2, Max: 7, AugMax: 7},
			"initiative": {Name: "Initiative", Min: 2, Max: 12, AugMax: 20},
			"intuition":  {Name: "Intuition", Min: 1, Max: 6, AugMax: 10},
			"logic":      {Name: "Logic", Min: 1, Max: 6, AugMax: 10},
			"magic":      {Name: "Magic", Min: 1, Max: 6, AugMax: 10},
			"reaction":   {Name: "Reaction", Min: 1, Max: 6, AugMax: 10},
			"resonance":  {Name: "Resonance", Min: 0, Max: 6, AugMax: 10},
			"strength":   {Name: "Strength", Min: 1, Max: 6, AugMax: 10},
			"willpower":  {Name: "Willpower", Min: 1, Max: 6, AugMax: 10},
		},
		Essence:             Attribute[float64]{Min: 0, Max: 6, AugMax: 6},
		QualityRestrictions: []string{},
		Qualities:           []string{},
		RuleSource:          shared.RuleSourceSR5Core,
	},
	"elf": {
		ID:          "elf",
		Name:        "Elf",
		PointCost:   40,
		Category:    CategoryMetahuman,
		Description: "Elves are known for their grace, beauty, and long lifespans.",
		Attributes: Attributes{
			"agility":    {Name: "Agility", Min: 2, Max: 7, AugMax: 11},
			"body":       {Name: "Body", Min: 1, Max: 6, AugMax: 10},
			"charisma":   {Name: "Charisma", Min: 3, Max: 8, AugMax: 12},
			"edge":       {Name: "Edge", Min: 2, Max: 7, AugMax: 7},
			"initiative": {Name: "Initiative", Min: 2, Max: 12, AugMax: 20},
			"intuition":  {Name: "Intuition", Min: 1, Max: 6, AugMax: 10},
			"logic":      {Name: "Logic", Min: 1, Max: 6, AugMax: 10},
			"magic":      {Name: "Magic", Min: 1, Max: 6, AugMax: 6},
			"reaction":   {Name: "Reaction", Min: 1, Max: 6, AugMax: 10},
			"resonance":  {Name: "Resonance", Min: 1, Max: 6, AugMax: 6},
			"strength":   {Name: "Strength", Min: 1, Max: 6, AugMax: 10},
			"willpower":  {Name: "Willpower", Min: 1, Max: 6, AugMax: 10},
		},
		Essence:             Attribute[float64]{Min: 0, Max: 6, AugMax: 6},
		QualityRestrictions: []string{},
		Qualities:           []string{"low_light_vision"},
		RuleSource:          shared.RuleSourceSR5Core,
	},
	"dwarf": {
		ID:          "dwarf",
		Name:        "Dwarf",
		PointCost:   50,
		Category:    CategoryMetahuman,
		Description: "Dwarves are known for their toughness, resilience, and their ability to see in the dark.",
		Attributes: Attributes{
			"agility":    {Name: "Agility", Min: 1, Max: 6, AugMax: 10},
			"body":       {Name: "Body", Min: 3, Max: 8, AugMax: 12},
			"charisma":   {Name: "Charisma", Min: 1, Max: 6, AugMax: 10},
			"edge":       {Name: "Edge", Min: 1, Max: 6, AugMax: 6},
			"initiative": {Name: "Initiative", Min: 2, Max: 11, AugMax: 19},
			"intuition":  {Name: "Intuition", Min: 1, Max: 6, AugMax: 10},
			"logic":      {Name: "Logic", Min: 1, Max: 6, AugMax: 10},
			"magic":      {Name: "Magic", Min: 1, Max: 6, AugMax: 6},
			"reaction":   {Name: "Reaction", Min: 1, Max: 5, AugMax: 9},
			"resonance":  {Name: "Resonance", Min: 1, Max: 6, AugMax: 6},
			"strength":   {Name: "Strength", Min: 3, Max: 8, AugMax: 12},
			"willpower":  {Name: "Willpower", Min: 2, Max: 7, AugMax: 11},
		},
		Essence:             Attribute[float64]{Min: 0, Max: 6, AugMax: 6},
		QualityRestrictions: []string{},
		Qualities:           []string{"thermographic_vision", "resistance_to_pathogens_toxins"},
		RuleSource:          shared.RuleSourceSR5Core,
		// <bonus>
		//     <lifestylecost>20</lifestylecost>
		// </bonus>
	},
	"ork": {
		ID:          "ork",
		Name:        "Ork",
		PointCost:   50,
		Category:    CategoryMetahuman,
		Description: "Orks are known for their strength, toughness, and tusks.",
		Attributes: Attributes{
			"agility":    {Name: "Agility", Min: 1, Max: 6, AugMax: 10},
			"body":       {Name: "Body", Min: 4, Max: 9, AugMax: 13},
			"charisma":   {Name: "Charisma", Min: 1, Max: 5, AugMax: 9},
			"edge":       {Name: "Edge", Min: 1, Max: 6, AugMax: 6},
			"initiative": {Name: "Initiative", Min: 2, Max: 12, AugMax: 20},
			"intuition":  {Name: "Intuition", Min: 1, Max: 6, AugMax: 10},
			"logic":      {Name: "Logic", Min: 1, Max: 5, AugMax: 9},
			"magic":      {Name: "Magic", Min: 1, Max: 6, AugMax: 6},
			"reaction":   {Name: "Reaction", Min: 1, Max: 6, AugMax: 10},
			"resonance":  {Name: "Resonance", Min: 1, Max: 6, AugMax: 6},
			"strength":   {Name: "Strength", Min: 3, Max: 8, AugMax: 12},
			"willpower":  {Name: "Willpower", Min: 1, Max: 6, AugMax: 10},
		},
		QualityRestrictions: []string{},
		Qualities:           []string{"low_light_vision"},
		RuleSource:          shared.RuleSourceSR5Core,
	},
	"troll": {
		ID:          "troll",
		Name:        "Troll",
		PointCost:   90,
		Category:    CategoryMetahuman,
		Description: "Trolls are known for their size, strength, and toughness.",
		Attributes: Attributes{
			"agility":    {Name: "Agility", Min: 1, Max: 5, AugMax: 9},
			"body":       {Name: "Body", Min: 5, Max: 10, AugMax: 14},
			"charisma":   {Name: "Charisma", Min: 1, Max: 4, AugMax: 8},
			"edge":       {Name: "Edge", Min: 1, Max: 6, AugMax: 6},
			"initiative": {Name: "Initiative", Min: 2, Max: 11, AugMax: 19},
			"intuition":  {Name: "Intuition", Min: 1, Max: 5, AugMax: 9},
			"logic":      {Name: "Logic", Min: 1, Max: 5, AugMax: 9},
			"magic":      {Name: "Magic", Min: 1, Max: 6, AugMax: 6},
			"reaction":   {Name: "Reaction", Min: 1, Max: 6, AugMax: 10},
			"resonance":  {Name: "Resonance", Min: 1, Max: 6, AugMax: 6},
			"strength":   {Name: "Strength", Min: 5, Max: 10, AugMax: 14},
			"willpower":  {Name: "Willpower", Min: 1, Max: 6, AugMax: 10},
		},
		Essence:             Attribute[float64]{Min: 0, Max: 6, AugMax: 6},
		QualityRestrictions: []string{},
		Qualities:           []string{"thermographic_vision"},
		RuleSource:          shared.RuleSourceSR5Core,
		// <bonus>
		//     <armor group="0">1</armor>
		//     <reach>1</reach>
		//     <lifestylecost>100</lifestylecost>
		// </bonus>
	},
}
