host: localhost
port: 33333
log_level: DEBUG
max_connections: 100
timeouts:
    idle: 30m
data:
    base_dir: _data
    test_dir: test/_data
    characters_dir: /characters
    zones_dir: /zones
    rooms_dir: /rooms
banned_names:
    - root
    - admin
    - god